apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-boot-config
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db-lb:5432/postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: testpassword